apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ctfd.fullname" . }}-config
data:
  CTFD_REDIS_URL: "redis://{{ include "ctfd.fullname" . }}-redis:{{ .Values.redis.port }}/0"
  CTFD_DATABASE_URL: "mysql+pymysql://{{ .Values.mariadb.username }}:`$(CTFD_DATABASE_PASSWORD)`@{{ .Values.mariadb.host }}:{{ .Values.mariadb.port }}/{{ .Values.mariadb.database }}"
  CTFD_LOG_LEVEL: "{{ .Values.ctfd.logLevel }}"
