apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctfd.fullname" . }}-secret
  labels:
    app: {{ include "ctfd.fullname" . }}
type: Opaque

stringData:
  CTFD_SECRET_KEY: "{{ .Values.ctfd.secretKey }}"
  {{- if not .Values.mariadb.existingSecret }}
  CTFD_DATABASE_PASSWORD: "{{ .Values.mariadb.password }}"
  {{- end }}
