apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  # Replace with your Cloudflare API token
  api-token: "CCTRvWZ6bp1Tesog_XvguWPqFIMNnvIH7Yc7xh4p"

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: r0963171@student.thomasmore.be
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - dns01:
          cloudflare:
            # Cloudflare API token with Zone:DNS:Edit permission
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-banaantje-be
  namespace: ctfd
spec:
  secretName: wildcard-tls
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: "ctfd,dynamic-instances"
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "*.banaantje.be"
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctfd-ingress
  namespace: ctfd
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "*.banaantje.be"
      secretName: wildcard-tls
  rules:
    - host: "ctf.banaantje.be"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctfd
                port:
                  number: 80